### ISSUE TITLE
This could help

### ISSUE THREAD

**Issue by lavender-sys** [NodeMine/NodeMine#1]
Not a real issue, but @Falkirks made https://github.com/Falkirks/DirtServer

**Comment by Magicode1** [comment]
Yeah, there is also MineJS. But we aren't looking to copy any code, we are doing it from scratch! :)

**Comment by falkirks** [comment]
@Magicode1 DirtServer doesn't have much implemented at all. But if you do notice that I implemented something faster or in a better way, feel free to use it. DirtServer doesn't have any license, so you could get into copyright issues. But you can take this note as my permission to use the DirtServer code without any restrictions. You don't need to acknowledge me as the author in any way.

**Comment by lavender-sys** [comment]
@Magicode1 Okay. I just remembered seeing DirtServer and I thought I would tell you about it. :)

**Comment by HittmanA** [comment]
@Falkirks I may not have to acknowledge you as an author, but if I use your code I wouldn't feel right about not mentioning you ;P
