### ISSUE TITLE
COOLL

### ISSUE THREAD

**Issue by matthew4444** [NodeMine/NodeMine#2]
COOOOOOOOLLLL :) :)

**Comment by daniktheboss** [comment]
Wtf bro. You will get banned fr

**Comment by matthew4444** [comment]
i love ur project, I must of not published the other comment, saying why I said that :( srry

**Comment by EdwardHamHam** [comment]
@matthew4444 But the project being cool (which it really is) isn't an issue. The issue tracker is for reporting bugs and errors. As for complimenting it online, I would recommend maybe... I don't know, tweeting about it?

**Comment by matthew4444** [comment]
ok, sorry bye

**Comment by HittmanA** [comment]
@Edwardthedog2 what makes it not cool exactly?

**Comment by EdwardHamHam** [comment]
@HittmanA No, I said it **is** cool.

**Comment by matthew4444** [comment]
@HittmanA  hittmana can u teach me python, plz , i want to be a better coder, i but my learning style is being told what to do, or i might get off task, plz ?
